[package]
name = "AptosShaker"
version = "0.0.1"

[dependencies]

AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-framework/", rev="randomnet" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-stdlib/", rev="randomnet" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-token/", rev="randomnet" }

[addresses]
dice_app ="_"
aptos_framework="0x1"
aptos_std="0x1"
aptos_token="0x3"
std="0x1"
